version: "2"
services:
  nginx:
    container_name: nginx
    image: sugnee_api/nginx:latest
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - .:/api
      - ./.docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    tty: true
    restart: always
  api:
    container_name: api
    image: sugnee_api/api:latest
    build:
      context: .
      dockerfile: ./.docker/api/Dockerfile
    environment:
      SESSION_DOMAIN: "localhost"
      SANCTUM_STATEFUL_DOMAINS: "localhost"
    volumes:
      - .:/api
    expose:
      - 9000
    tty: true
    restart: always
    depends_on:
      - db

  db:
    container_name: db
    image: "postgres:10-alpine"
    restart: always
    environment:
      - POSTGRES_DB=next
      - POSTGRES_USER=next
      - POSTGRES_PASSWORD=next
    ports:
      - 5433:5432
