version: "2"
services:
  nginx:
    container_name: nginx
    image: sugnee_api/nginx:latest
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - .:/api
      - ./.docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    tty: true
    restart: always
  api:
    container_name: api
    image: sugnee_api/api:latest
    build:
      context: .
      dockerfile: ./.docker/api/Dockerfile
    environment:
      SESSION_DOMAIN: "localhost"
      SANCTUM_STATEFUL_DOMAINS: "localhost"
    volumes:
      - .:/api
    expose:
      - 9000
    tty: true
    restart: always
    depends_on:
      - db

  db:
    container_name: db
    image: "postgres:10-alpine"
    restart: always
    environment:
      - POSTGRES_DB=benchi
      - POSTGRES_USER=benchi
      - POSTGRES_PASSWORD=benchi
    ports:
      - 5433:5432
  db2:
    container_name: db2
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=fukuriku2
      - POSTGRES_USER=fukuriku2
      - POSTGRES_PASSWORD=password
    ports:
      - "5434:5432"
  pgadmin4:
    image: dpage/pgadmin4:4.2
    container_name: pgadmin4
    ports:
      - 5050:80
    volumes:
      - ./docker/pgadmin4:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin4
    depends_on:
      - db
      - db2
    restart: always
volumes:
  db:
  db2:
